name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Format & Lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '24.3.3'
        elixir-version: '1.13.4'
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Format
      run: mix format --check-formatted 
    - name: Lint
      run: mix credo --strict
  build:
    runs-on: ${{ matrix.os }} 
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        otp: ['24.3.3']
        elixir: ['1.13.4']
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: mix deps.get --only test
    - name: Run Tests
      run: mix test